package com.github.cplexopl.actions

import com.github.cplexopl.OplFileType
import com.intellij.notification.NotificationGroupManager
import com.intellij.notification.NotificationType
import com.intellij.openapi.actionSystem.ActionUpdateThread
import com.intellij.openapi.actionSystem.AnAction
import com.intellij.openapi.actionSystem.AnActionEvent
import com.intellij.openapi.actionSystem.CommonDataKeys
import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.fileEditor.FileEditorManager
import com.intellij.openapi.ui.Messages
import com.intellij.openapi.vfs.VirtualFile
import com.intellij.psi.PsiManager

class GeneratePythonRunnerAction : AnAction() {

    override fun getActionUpdateThread(): ActionUpdateThread = ActionUpdateThread.BGT

    override fun actionPerformed(e: AnActionEvent) {
        val project = e.project ?: return
        val file = e.getData(CommonDataKeys.VIRTUAL_FILE) ?: return

        val baseName = file.nameWithoutExtension
        val dir = file.parent

        val pyFileName = "${baseName}_runner.py"

        val datFile = dir.findChild("$baseName.dat")
        val hasDat = datFile != null

        // Check if file already exists
        if (dir.findChild(pyFileName) != null) {
            val result = Messages.showYesNoDialog(
                project,
                "File $pyFileName already exists. Overwrite?",
                "Generate Python Runner",
                Messages.getQuestionIcon()
            )
            if (result != Messages.YES) return
        }

        ApplicationManager.getApplication().runWriteAction {
            try {
                // If the file exists, get it, otherwise create it
                val pyFile = dir.findChild(pyFileName) ?: dir.createChildData(this, pyFileName)
                
                // Write content
                val content = generatePythonContent(baseName, hasDat)
                pyFile.setBinaryContent(content.toByteArray(Charsets.UTF_8))

                // Open in editor
                FileEditorManager.getInstance(project).openFile(pyFile, true)

                // Show notification
                NotificationGroupManager.getInstance()
                    .getNotificationGroup("CPLEX OPL")
                    .createNotification(
                        "Generated Python Runner for $baseName",
                        "Please ensure doopl is installed to run the script. Run: pip install doopl",
                        NotificationType.INFORMATION
                    )
                    .addAction(
                        com.intellij.notification.NotificationAction.createSimpleExpiring("Install doopl") {
                            try {
                                com.intellij.execution.configurations.GeneralCommandLine("pip", "install", "doopl").createProcess()
                                Messages.showInfoMessage(project, "doopl installation started in background.", "Installation")
                            } catch (e: Exception) {
                                Messages.showErrorDialog(project, "Failed to start pip: ${e.message}", "Error")
                            }
                        }
                    )
                    .notify(project)
            } catch (ex: Exception) {
                Messages.showErrorDialog(project, "Error creating file: ${ex.message}", "Error")
            }
        }
    }

    override fun update(e: AnActionEvent) {
        val file = e.getData(CommonDataKeys.VIRTUAL_FILE)
        e.presentation.isEnabledAndVisible = file?.fileType == OplFileType
    }

    private fun generatePythonContent(baseName: String, hasDat: Boolean): String {
        val datArg = if (hasDat) ", data=\"$baseName.dat\"" else ""

        return """
# Generated by CPLEX OPL Plugin for JetBrains
# Requirements: pip install doopl
# Documentation: https://github.com/IBMDecisionOptimization/doopl

from doopl.factory import create_opl_model

def run_model():
    # Create an OPL model from a .mod and (optionally) .dat file
    with create_opl_model(model="$baseName.mod"$datArg) as opl:
        
        # Run the model
        opl.run()
        
        # Results are available in opl.report as Pandas DataFrames
        print("Model solved successfully!")
        
        # Example of printing all output tables:
        # for name, table in opl.report.items():
        #     print(f"Table: {name}")
        #     print(table)

if __name__ == "__main__":
    run_model()
""".trimIndent()
    }
}
